---

- name: vlan provisioning
  hosts: leaf
  connection: local
  gather_facts: no
  vars:
    vname: name_1
    vid: 61 
    vrange: "2-10,20,50,55-60"

  tasks:

    - name: ensure vlan exists
      nxos_vlan: vlan_id={{ vid }} state=present host={{ inventory_hostname }} 
      with_items: abc
    - name: ensure vlan range  exists
      nxos_vlan: vlan_range={{ vrange }} state=present host={{ inventory_hostname }} 
      with_items: abc 
